# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_id',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HRApp.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HRApp.Company'),
            preserve_default=False,
        ),
    ]
