# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRApp', '0003_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('HR', 'HR Personnel'), ('SME', 'SME took interview of Applicant on HR Personnel Email'), ('A', 'Applicant')], default='A', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='apply',
            name='document',
            field=models.FileField(upload_to='media'),
        ),
    ]
