# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0004_auto_20170422_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(default='A', max_length=3),
        ),
    ]
