# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 19:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRApp', '0005_auto_20170426_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField()),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRApp.Apply')),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
