# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 20:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0006_rateapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateapply',
            name='rate',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
